name: Verify

on:
  pull_request:
  merge_group:
  push:
    branches:
      - dev/v*/v*
      - alpha/v*/v*
      - release/v*/v*
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  pull-requests: read

jobs:
  check:
    uses: kungfu-systems/buildchain/.github/workflows/public-build-check.yml@v4-alpha
    with:
      buildchain-ref: v4-alpha
      require-version-state: true
      upload-artifacts: true
      mode: source
